### ISSUE TITLE
Upgrade `@storybook/node-logger` to v7

### ISSUE THREAD

**Issue by nicdford** [0xTheProDev/storybook-addon-sass-postcss#6]
After upgrading to storybook v7.1 I get a "Attention: The following dependencies are duplicated which might cause unexpected behavior". I think this is because this package is using an older version of node-logger?

```
├─┬ @storybook/addon-essentials@7.1.1
│ └── @storybook/node-logger@7.1.1
├─┬ @storybook/addon-styling@1.3.4
│ └── @storybook/node-logger@7.1.1 deduped
└─┬ storybook-addon-sass-postcss@0.1.3
  └── @storybook/node-logger@6.5.16
```

**Comment by 0xTheProDev** [comment]
Hi @nicdford , thanks for pointing out. I hope it would not be much of an ask to open up a PR for the same.

**Comment by 0xTheProDev** [comment]
Hi @nicdford, following the effort to make this lib compatible with @storybook v8, the necessary change has been done. Closing now!
